// <auto-generated />
using System;
using Analytics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analytics.Api.Data.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260918134256_AddInsightSnapshotSchema")]
    partial class AddInsightSnapshotSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Api.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstagramUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfessionalAccountType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("InstagramUserId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Username");

                    b.ToTable("InstagramAccounts", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramCredentials.Domain.InstagramCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("InstagramAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRefreshedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("InstagramAccountId")
                        .IsUnique();

                    b.ToTable("InstagramCredentials", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramIntegration.Domain.InstagramOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("StateHash")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "ExpiresAtUtc");

                    b.ToTable("InstagramOAuthStates", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.AccountCurrentStats", b =>
                {
                    b.Property<Guid>("InstagramAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("FollowersCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("FollowsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediaCount")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("InstagramAccountId");

                    b.ToTable("AccountCurrentStats", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.AccountInsightSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AccountsEngagedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("FollowerCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InstagramAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ProfileViewsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReachCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SourceTimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("TotalInteractionsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ViewsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("WebsiteClicksCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("InstagramAccountId", "CapturedAtUtc")
                        .IsUnique()
                        .IsDescending(false, true);

                    b.ToTable("AccountInsightSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountInsightSnapshots_NonNegativeMetrics", "([ViewsCount] IS NULL OR [ViewsCount] >= 0) AND ([ReachCount] IS NULL OR [ReachCount] >= 0) AND ([FollowerCount] IS NULL OR [FollowerCount] >= 0) AND ([ProfileViewsCount] IS NULL OR [ProfileViewsCount] >= 0) AND ([WebsiteClicksCount] IS NULL OR [WebsiteClicksCount] >= 0) AND ([AccountsEngagedCount] IS NULL OR [AccountsEngagedCount] >= 0) AND ([TotalInteractionsCount] IS NULL OR [TotalInteractionsCount] >= 0)");
                        });
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.InstagramMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(2200)
                        .HasColumnType("nvarchar(2200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstagramAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstagramMediaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InstagramAccountId", "InstagramMediaId")
                        .IsUnique();

                    b.HasIndex("InstagramAccountId", "PublishedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("InstagramMedia", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.MediaCurrentStats", b =>
                {
                    b.Property<Guid>("InstagramMediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CommentsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaysCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReachCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SavesCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("SharesCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SourceTimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("InstagramMediaId");

                    b.ToTable("MediaCurrentStats", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.MediaImportCheckpoint", b =>
                {
                    b.Property<Guid>("InstagramAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterCursor")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("int");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("PagesProcessed")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("InstagramAccountId");

                    b.ToTable("MediaImportCheckpoints", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.MediaInsightSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AverageWatchTimeMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CommentsCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InstagramMediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LikesCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReachCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("SavesCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("SharesCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SourceTimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("TotalInteractionsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalWatchTimeMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("InstagramMediaId", "CapturedAtUtc")
                        .IsUnique()
                        .IsDescending(false, true);

                    b.ToTable("MediaInsightSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaInsightSnapshots_NonNegativeMetrics", "([ViewsCount] IS NULL OR [ViewsCount] >= 0) AND ([ReachCount] IS NULL OR [ReachCount] >= 0) AND ([LikesCount] IS NULL OR [LikesCount] >= 0) AND ([CommentsCount] IS NULL OR [CommentsCount] >= 0) AND ([SavesCount] IS NULL OR [SavesCount] >= 0) AND ([SharesCount] IS NULL OR [SharesCount] >= 0) AND ([TotalInteractionsCount] IS NULL OR [TotalInteractionsCount] >= 0) AND ([AverageWatchTimeMilliseconds] IS NULL OR [AverageWatchTimeMilliseconds] >= 0) AND ([TotalWatchTimeMilliseconds] IS NULL OR [TotalWatchTimeMilliseconds] >= 0)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", b =>
                {
                    b.HasOne("Analytics.Api.Identity.ApplicationUser", "Owner")
                        .WithMany("InstagramAccounts")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Analytics.Api.InstagramCredentials.Domain.InstagramCredential", b =>
                {
                    b.HasOne("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", "InstagramAccount")
                        .WithOne("Credential")
                        .HasForeignKey("Analytics.Api.InstagramCredentials.Domain.InstagramCredential", "InstagramAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramAccount");
                });

            modelBuilder.Entity("Analytics.Api.InstagramIntegration.Domain.InstagramOAuthState", b =>
                {
                    b.HasOne("Analytics.Api.Identity.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.AccountCurrentStats", b =>
                {
                    b.HasOne("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", "InstagramAccount")
                        .WithOne()
                        .HasForeignKey("Analytics.Api.InstagramMedia.Domain.AccountCurrentStats", "InstagramAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramAccount");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.AccountInsightSnapshot", b =>
                {
                    b.HasOne("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", "InstagramAccount")
                        .WithMany()
                        .HasForeignKey("InstagramAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramAccount");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.InstagramMedia", b =>
                {
                    b.HasOne("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", "InstagramAccount")
                        .WithMany()
                        .HasForeignKey("InstagramAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramAccount");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.MediaCurrentStats", b =>
                {
                    b.HasOne("Analytics.Api.InstagramMedia.Domain.InstagramMedia", "InstagramMedia")
                        .WithOne("CurrentStats")
                        .HasForeignKey("Analytics.Api.InstagramMedia.Domain.MediaCurrentStats", "InstagramMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramMedia");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.MediaImportCheckpoint", b =>
                {
                    b.HasOne("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", "InstagramAccount")
                        .WithOne()
                        .HasForeignKey("Analytics.Api.InstagramMedia.Domain.MediaImportCheckpoint", "InstagramAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramAccount");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.MediaInsightSnapshot", b =>
                {
                    b.HasOne("Analytics.Api.InstagramMedia.Domain.InstagramMedia", "InstagramMedia")
                        .WithMany()
                        .HasForeignKey("InstagramMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramMedia");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Analytics.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Analytics.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analytics.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Analytics.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Analytics.Api.Identity.ApplicationUser", b =>
                {
                    b.Navigation("InstagramAccounts");
                });

            modelBuilder.Entity("Analytics.Api.InstagramAccounts.Domain.InstagramAccount", b =>
                {
                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Analytics.Api.InstagramMedia.Domain.InstagramMedia", b =>
                {
                    b.Navigation("CurrentStats");
                });
#pragma warning restore 612, 618
        }
    }
}
